do_token = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
ssh_key_file = "<Full Path To My Key.pub"
vpc_name = "prod-vpc"
db_cluster_name = "prod-db-cluster"
db_name = "prod-db"
domain_name = "your_domain_name.com"