do_token = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
ssh_key_file = "<Full Path To My Key.pub>"
vpc_name = "test-vpc"
db_cluster_name = "test-db-cluster"
db_name = "test-db"
domain_name = "<your_domain_name.com>"